[package]
name = "meliusgfx"
version = "0.1.0"
edition = "2018"
authors = ["PutterBeanut <putterbeanutdev@gmail.com>"]
description = "Safe OpenGL wrapper for Melius"

[dependencies]
gl = "0.14.0"
cgmath = "0.18.0"
glfw = "0.41.0"
image = "0.23.14"